// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChtmXOeuxrr8Fm_dpfUS3w01m_T9C4Ekg',
    appId: '1:250971823344:web:e02b722e7a7fffec18f635',
    messagingSenderId: '250971823344',
    projectId: 'flutterfirebasedemo-c9d09',
    authDomain: 'flutterfirebasedemo-c9d09.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo-c9d09.firebasestorage.app',
    measurementId: 'G-84FZ5B99CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7PAqp8NjhsM63TqE52px1oXpvu-mAW68',
    appId: '1:250971823344:android:1baf11ad405f1f7f18f635',
    messagingSenderId: '250971823344',
    projectId: 'flutterfirebasedemo-c9d09',
    storageBucket: 'flutterfirebasedemo-c9d09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH0m3gwjPAICXqgOf06umpibKlh-I_sWQ',
    appId: '1:250971823344:ios:a3a132cf3f91acfe18f635',
    messagingSenderId: '250971823344',
    projectId: 'flutterfirebasedemo-c9d09',
    storageBucket: 'flutterfirebasedemo-c9d09.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH0m3gwjPAICXqgOf06umpibKlh-I_sWQ',
    appId: '1:250971823344:ios:a3a132cf3f91acfe18f635',
    messagingSenderId: '250971823344',
    projectId: 'flutterfirebasedemo-c9d09',
    storageBucket: 'flutterfirebasedemo-c9d09.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChtmXOeuxrr8Fm_dpfUS3w01m_T9C4Ekg',
    appId: '1:250971823344:web:f651e1bf0ad666e018f635',
    messagingSenderId: '250971823344',
    projectId: 'flutterfirebasedemo-c9d09',
    authDomain: 'flutterfirebasedemo-c9d09.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo-c9d09.firebasestorage.app',
    measurementId: 'G-B8MLGBEB3M',
  );

}